apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'user_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8080']
            labels:
              application: 'User Microservice Application'
      - job_name: 'events_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['events-service:8060']
            labels:
              application: 'User Microservice Application'        
      - job_name: 'api_gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-gateway:9761']
            labels:
              application: 'API Gateway Application'
      - job_name: 'notification_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-service:9010']
            labels:
              application: 'Notification Service Application'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: F:\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:

      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.37.1
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yml
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-claim0
          persistentVolumeClaim:
            claimName: prometheus-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-claim0
  name: prometheus-claim0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---